/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8dc02d7a-3f20-4629-9cf3-2578dddccdf3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_nKal4OH6a",
    "aws_user_pools_web_client_id": "5r0ne7e30j01g7hkgbrpun4k9g",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://iwgcge7pf5fy7ekksfstiwiudq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fr37p3dgq5aohgbbcftud6qhdm",
    "aws_user_files_s3_bucket": "saucar954d2abf78d24adc98a8066bbdd24ef8173452-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
